<script>
	import '../app.css';
	let { children } = $props();
</script>

<svelte:head>
	<title>Words Not Code — Turn your app idea into a technical blueprint</title>
	<meta name="description" content="Describe your app idea in plain English and get a comprehensive technical blueprint you can paste into AI coding assistants like Claude, ChatGPT, Cursor, or Gemini." />

	<!-- Open Graph -->
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Words Not Code — Turn your app idea into a technical blueprint" />
	<meta property="og:description" content="Answer 17 simple questions about your app idea and get a complete technical spec you can paste into any AI coding assistant. Free, no sign-up required." />
	<meta property="og:site_name" content="Words Not Code" />
	<meta property="og:url" content="https://wordsnotcode.com" />

	<!-- Twitter Card -->
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Words Not Code — App Idea to Blueprint" />
	<meta name="twitter:description" content="Answer simple questions. Get a complete technical spec. Paste it into any AI coding assistant and start building." />

	<!-- JSON-LD Structured Data: WebApplication -->
	{@html `<script type="application/ld+json">${JSON.stringify({
		"@context": "https://schema.org",
		"@type": "WebApplication",
		"name": "Words Not Code",
		"description": "Turn your app idea into a technical blueprint by answering simple questions. Get a complete spec you can paste into any AI coding assistant.",
		"url": "https://wordsnotcode.com",
		"applicationCategory": "DeveloperApplication",
		"operatingSystem": "Any",
		"offers": {
			"@type": "Offer",
			"price": "0",
			"priceCurrency": "USD"
		}
	})}</script>`}

	<!-- JSON-LD Structured Data: FAQPage -->
	{@html `<script type="application/ld+json">${JSON.stringify({
		"@context": "https://schema.org",
		"@type": "FAQPage",
		"mainEntity": [
			{
				"@type": "Question",
				"name": "What is Words Not Code?",
				"acceptedAnswer": {
					"@type": "Answer",
					"text": "Words Not Code is a free web app that turns your app idea into a comprehensive technical blueprint. You answer simple questions in plain English — no coding knowledge required — and get a detailed spec you can hand to an AI coding assistant to start building immediately."
				}
			},
			{
				"@type": "Question",
				"name": "How does Words Not Code work?",
				"acceptedAnswer": {
					"@type": "Answer",
					"text": "You walk through a guided wizard of 17 plain-English questions about your app idea — things like what problem it solves, who the users are, and what features it needs. At the end, Words Not Code generates a complete technical blueprint document that you can copy and paste into any AI coding assistant."
				}
			},
			{
				"@type": "Question",
				"name": "Is Words Not Code free?",
				"acceptedAnswer": {
					"@type": "Answer",
					"text": "Yes, Words Not Code is completely free to use. There is no sign-up, no account required, and no hidden fees. Just open the site and start describing your app idea."
				}
			},
			{
				"@type": "Question",
				"name": "What AI coding assistants can I use with the blueprint?",
				"acceptedAnswer": {
					"@type": "Answer",
					"text": "The blueprint generated by Words Not Code works with any AI coding assistant, including Claude, ChatGPT, Cursor, GitHub Copilot, Gemini, and others. Simply copy the blueprint and paste it into your preferred assistant to start building your app."
				}
			}
		]
	})}</script>`}

	<!-- JSON-LD Structured Data: HowTo -->
	{@html `<script type="application/ld+json">${JSON.stringify({
		"@context": "https://schema.org",
		"@type": "HowTo",
		"name": "How to turn your app idea into a technical blueprint",
		"description": "Use Words Not Code to go from app idea to technical blueprint in minutes, then paste it into an AI coding assistant to start building.",
		"step": [
			{
				"@type": "HowToStep",
				"name": "Describe your app idea",
				"text": "Answer 17 simple, plain-English questions about your app — what it does, who it's for, and what features it needs."
			},
			{
				"@type": "HowToStep",
				"name": "Generate your blueprint",
				"text": "Words Not Code compiles your answers into a comprehensive technical blueprint covering architecture, features, data models, and more."
			},
			{
				"@type": "HowToStep",
				"name": "Paste into an AI coding assistant",
				"text": "Copy the generated blueprint and paste it into Claude, ChatGPT, Cursor, Gemini, or any other AI coding assistant to start building your app."
			}
		]
	})}</script>`}
</svelte:head>

{@render children()}
